### ISSUE TITLE
NoMethodError from README.md Example Snippet

### ISSUE THREAD

**Issue by johnknapprs** [partydrone/connect-sdk-ruby#3]
## Describe the bug

Following the example code block results in the following error: 

```ruby
require 'op_connect'

client = OpConnect::Client.new(api_endpoint: ENV['api_endpoint'], access_token: ENV['access_token'])
puts client.vaults
```

```shell
NoMethodError: undefined method `map' for #<String:0x00007fb334a38ec0>
Did you mean?  tap
/usr/local/lib/ruby/gems/2.7.0/gems/op_connect-0.1.1/lib/op_connect/client/vaults.rb:5:in `list_vaults'
/Users/johnknapp/repos/runbook/customer_onboarding/Rakefile:79:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
```

## To Reproduce
- Copy code snippet from README.md
- Update `api_endpoint` and `access_token` to working values
- Run script to print vaults

## Expected behavior

Does not crash trying to call `map` on a String object

## Environment
 - Gem version: 0.1.1
 - Ruby version: 2.7.5

**Comment by partydrone** [comment]
@johnknapprs, I am unable to reproduce this error. I tried it with no 1Password Connect servers running and I get a TCP connection error, but not the error you describe. If I use the code snippet from your post—with the endpoint and the access token configured correctly—with the Connect servers running, I get the expected output:

```ruby
[4] pry(main)> client = OpConnect::Client.new(api_endpoint: ENV['OP_CONNECT_API_ENDPOINT'], access_token: ENV['OP_CONNECT_ACCESS_TOKEN'])
=> #<OpConnect::Client:0x0000aaab0192bf38 ...>
[5] pry(main)> client.inspect
=> "#<OpConnect::Client:0x0000aaab0192bf38 @access_token=\"************************\", @adapter=:net_http, @api_endpoint=\"http://op-connect-api:8080/v1\", @stubs=nil, @user_agent=\"1Password Connect Ruby SDK 0.1.1\">"
[6] pry(main)> client.vaults
=> [#<OpConnect::Vault:0x0000aaab011df518 @attribute_version=2, @content_version=3, @created_at=2021-10-19 22:24:50 UTC, @id="alynbizzypgx62nti6zxajloei", @items=2, @name="SDK Development", @type="USER_CREATED", @updated_at=2021-12-12 06:17:00 UTC>]
```

Can you tell me more about your environment? What is your API endpoint set to and do you have a Connect API service running there?
