### ISSUE TITLE
Vendor data present since version 0.1.2

### ISSUE THREAD

**Issue by galaktipus** [partydrone/connect-sdk-ruby#5]
### Version

0.1.2

### Description

Hey there,

My name is Tamir and I run security & quality assessment for Ruby libraries using Diffend.io.

While reviewing the changes for this lib, I noticed, that the vendor directory is being included.

Is this needed? Usually, it's added by mistake and causes:

a) confusion
b) problems when tracking changes
c) extensive library size

ref: [LINK](https://rubygems.org/gems/op_connect/versions/0.1.2)

Note that the package size grew from 17KB to 12.9MB due to the new vender added.

If the presence of vendor data is valid I would love the reasoning. Thanks!

**Comment by partydrone** [comment]
Thanks for catching that @galaktipus.
